# Generated by Django 4.2.7 on 2025-10-22 18:16

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0014_payment_batch_number_payment_notes_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_hotel_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único de la factura', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('A', 'Factura A (Responsable Inscripto)'), ('B', 'Factura B (Consumidor Final)'), ('C', 'Factura C (Exento)'), ('E', 'Factura E (Exportación)'), ('NC', 'Nota de Crédito'), ('ND', 'Nota de Débito')], help_text='Tipo de comprobante según AFIP', max_length=2)),
                ('number', models.CharField(help_text='Número de factura formateado (0001-00001234)', max_length=13)),
                ('issue_date', models.DateField(help_text='Fecha de emisión de la factura')),
                ('cae', models.CharField(blank=True, help_text='Código de Autorización Electrónico de AFIP', max_length=14)),
                ('cae_expiration', models.DateField(blank=True, help_text='Fecha de vencimiento del CAE', null=True)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total de la factura', max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de IVA', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Monto neto (sin IVA)', max_digits=12)),
                ('currency', models.CharField(default='ARS', help_text='Moneda de la factura', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada a AFIP'), ('approved', 'Aprobada por AFIP'), ('error', 'Error en AFIP'), ('cancelled', 'Cancelada')], default='draft', help_text='Estado actual de la factura', max_length=20)),
                ('pdf_file', models.FileField(blank=True, help_text='Archivo PDF de la factura', null=True, upload_to='invoices/pdf/%Y/%m/%d/')),
                ('pdf_url', models.URLField(blank=True, help_text='URL del PDF en almacenamiento externo')),
                ('afip_response', models.JSONField(blank=True, default=dict, help_text='Respuesta completa de AFIP')),
                ('client_name', models.CharField(help_text='Nombre del cliente', max_length=200)),
                ('client_document_type', models.CharField(default='96', help_text='Tipo de documento del cliente', max_length=2)),
                ('client_document_number', models.CharField(help_text='Número de documento del cliente', max_length=20)),
                ('client_tax_condition', models.CharField(choices=[('1', 'Responsable Inscripto'), ('5', 'Consumidor Final'), ('6', 'Exento'), ('7', 'No Responsable'), ('8', 'Monotributo'), ('9', 'Monotributo Social')], default='5', help_text='Condición de IVA del cliente', max_length=2)),
                ('client_address', models.TextField(blank=True, help_text='Dirección del cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Número de intentos de envío a AFIP')),
                ('last_error', models.TextField(blank=True, help_text='Último error registrado')),
                ('sent_to_afip_at', models.DateTimeField(blank=True, help_text='Fecha y hora de envío a AFIP', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Fecha y hora de aprobación por AFIP', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó la factura', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(help_text='Hotel que emite la factura', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.hotel')),
                ('payment', models.ForeignKey(blank=True, help_text='Pago asociado a la factura', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='reservations.payment')),
                ('reservation', models.ForeignKey(help_text='Reserva asociada a la factura', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Descripción del item', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Cantidad', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio unitario', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal (quantity * unit_price)', max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), help_text='Alicuota de IVA (%)', max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, help_text='Monto de IVA del item', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total del item (subtotal + vat_amount)', max_digits=12)),
                ('afip_code', models.CharField(default='1', help_text='Código de producto/servicio AFIP', max_length=20)),
                ('invoice', models.ForeignKey(help_text='Factura a la que pertenece el item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.invoice')),
            ],
            options={
                'verbose_name': 'Item de Factura',
                'verbose_name_plural': 'Items de Factura',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AfipConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(help_text='CUIT del hotel (11 dígitos)', max_length=11)),
                ('tax_condition', models.CharField(choices=[('1', 'Responsable Inscripto'), ('5', 'Consumidor Final'), ('6', 'Exento'), ('7', 'No Responsable'), ('8', 'Monotributo'), ('9', 'Monotributo Social')], default='1', help_text='Condición de IVA del hotel', max_length=2)),
                ('point_of_sale', models.PositiveIntegerField(default=1, help_text='Punto de venta AFIP (1-9999)')),
                ('certificate_path', models.CharField(help_text='Ruta al certificado AFIP (.crt)', max_length=500)),
                ('private_key_path', models.CharField(help_text='Ruta a la clave privada AFIP (.key)', max_length=500)),
                ('environment', models.CharField(choices=[('test', 'Testing'), ('production', 'Producción')], default='test', help_text='Ambiente de AFIP (test/production)', max_length=20)),
                ('last_invoice_number', models.PositiveIntegerField(default=0, help_text='Último número de factura emitido')),
                ('last_cae_date', models.DateTimeField(blank=True, help_text='Fecha del último CAE emitido', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la configuración está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó la configuración', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.OneToOneField(help_text='Hotel asociado a esta configuración', on_delete=django.db.models.deletion.CASCADE, related_name='afip_config', to='core.hotel')),
            ],
            options={
                'verbose_name': 'Configuración AFIP',
                'verbose_name_plural': 'Configuraciones AFIP',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['hotel', 'status'], name='invoicing_i_hotel_i_9ee666_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['reservation'], name='invoicing_i_reserva_02e5c5_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['type', 'issue_date'], name='invoicing_i_type_3593ce_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['cae'], name='invoicing_i_cae_310e18_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['number'], name='invoicing_i_number_fe55ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('hotel', 'number'), name='unique_invoice_number_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='afipconfig',
            index=models.Index(fields=['hotel', 'is_active'], name='invoicing_a_hotel_i_48b85e_idx'),
        ),
        migrations.AddIndex(
            model_name='afipconfig',
            index=models.Index(fields=['environment'], name='invoicing_a_environ_f6af78_idx'),
        ),
    ]
