# Generated by Django 4.2.7 on 2025-10-23 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='related_invoice',
            field=models.ForeignKey(blank=True, help_text='Factura original para notas de crédito/débito', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_documents', to='invoicing.invoice'),
        ),
    ]
