# Generated by Django 4.2.7 on 2025-10-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_invoice_related_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='afipconfig',
            name='afip_sign',
            field=models.TextField(blank=True, help_text='Firma asociada al TA'),
        ),
        migrations.AddField(
            model_name='afipconfig',
            name='afip_token',
            field=models.TextField(blank=True, help_text='Último Token de Acceso (WSAA)'),
        ),
        migrations.AddField(
            model_name='afipconfig',
            name='afip_token_expiration',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora de expiración del TA (WSAA)', null=True),
        ),
        migrations.AddField(
            model_name='afipconfig',
            name='afip_token_generation',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora de generación del TA (WSAA)', null=True),
        ),
        migrations.AddIndex(
            model_name='afipconfig',
            index=models.Index(fields=['afip_token_expiration'], name='invoicing_a_afip_to_e96858_idx'),
        ),
    ]
