# Generated by Django 4.2.7 on 2025-10-25 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_payment_batch_number_payment_notes_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_hotel_logo'),
        ('invoicing', '0003_afipconfig_afip_sign_afipconfig_afip_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afipconfig',
            name='last_receipt_number',
            field=models.PositiveIntegerField(default=0, help_text='Último número de comprobante emitido'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único del comprobante', primary_key=True, serialize=False)),
                ('number', models.CharField(help_text='Número de comprobante formateado (RC-0001-00001234)', max_length=13)),
                ('issue_date', models.DateField(help_text='Fecha de emisión del comprobante')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del comprobante', max_digits=12)),
                ('currency', models.CharField(default='ARS', help_text='Moneda del comprobante', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('issued', 'Emitido'), ('cancelled', 'Cancelado')], default='draft', help_text='Estado actual del comprobante', max_length=20)),
                ('pdf_file', models.FileField(blank=True, help_text='Archivo PDF del comprobante', null=True, upload_to='receipts/pdf/%Y/%m/%d/')),
                ('pdf_url', models.URLField(blank=True, help_text='URL del PDF en almacenamiento externo')),
                ('client_name', models.CharField(help_text='Nombre del cliente', max_length=200)),
                ('client_document_type', models.CharField(default='96', help_text='Tipo de documento del cliente', max_length=2)),
                ('client_document_number', models.CharField(help_text='Número de documento del cliente', max_length=20)),
                ('client_address', models.TextField(blank=True, help_text='Dirección del cliente')),
                ('client_city', models.CharField(blank=True, help_text='Ciudad del cliente', max_length=100)),
                ('client_postal_code', models.CharField(blank=True, help_text='Código postal del cliente', max_length=20)),
                ('client_country', models.CharField(default='Argentina', help_text='País del cliente', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el comprobante', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(help_text='Hotel que emite el comprobante', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.hotel')),
                ('payment', models.ForeignKey(help_text='Pago asociado al comprobante', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='reservations.payment')),
                ('reservation', models.ForeignKey(help_text='Reserva asociada al comprobante', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reservation', 'created_at'], name='invoicing_r_reserva_8017b9_idx'), models.Index(fields=['hotel', 'status'], name='invoicing_r_hotel_i_0e1218_idx'), models.Index(fields=['number'], name='invoicing_r_number_e1cf81_idx')],
            },
        ),
    ]
