# Generated by Django 4.2.7 on 2025-10-25 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_payment_is_deposit_payment_metadata'),
        ('invoicing', '0004_afipconfig_last_receipt_number_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afipconfig',
            name='last_receipt_number',
        ),
        migrations.AddField(
            model_name='afipconfig',
            name='invoice_mode',
            field=models.CharField(choices=[('receipt_only', 'Solo Recibos'), ('fiscal_on_deposit', 'Facturación en Seña')], default='receipt_only', help_text='Modo de facturación para pagos parciales (señas)', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payments_data',
            field=models.JSONField(blank=True, default=list, help_text='Lista de IDs de pagos asociados a esta factura (incluye señas y pagos finales)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Pago principal asociado a la factura (para compatibilidad)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='reservations.payment'),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
