# Generated by Django 4.2.7 on 2025-09-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_hotel_country_alter_hotel_city'),
        ('rooms', '0004_alter_room_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=120)),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('check_in', 'Check-in'), ('check_out', 'Check-out'), ('no_show', 'No-show'), ('early_check_in', 'Check-in anticipado'), ('late_check_out', 'Check-out tardío')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='rooms.room')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hotel', 'room'], name='reservation_hotel_i_6c4521_idx'), models.Index(fields=['hotel', 'check_in'], name='reservation_hotel_i_bd38fd_idx'), models.Index(fields=['status'], name='reservation_status_f1a03a_idx')],
            },
        ),
    ]
