# Generated by Django 4.2.7 on 2025-09-20 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_hotel_country_alter_hotel_city'),
        ('rooms', '0004_alter_room_hotel'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('block_type', models.CharField(choices=[('maintenance', 'Mantenimiento'), ('out_of_service', 'Fuera de servicio'), ('hold', 'Bloqueo')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_blocks', to='core.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_blocks', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Bloqueo de habitación',
                'verbose_name_plural': 'Bloqueos de habitaciones',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['hotel', 'room'], name='reservation_hotel_i_d999f3_idx'), models.Index(fields=['hotel', 'start_date'], name='reservation_hotel_i_c28ef2_idx'), models.Index(fields=['is_active'], name='reservation_is_acti_ff7dda_idx')],
            },
        ),
    ]
