# Generated by Django 4.2.7 on 2025-09-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guests_data',
            field=models.JSONField(default=list, help_text='Información de todos los huéspedes'),
        ),
    ]
