# Generated by Django 4.2.7 on 2025-09-27 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_guests_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='guest_email',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guest_name',
        ),
    ]
