# Generated by Django 4.2.7 on 2025-09-30 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_extra_guest_fee_room_max_capacity_and_more'),
        ('core', '0006_alter_hotel_enterprise_delete_enterprise'),
        ('reservations', '0005_remove_reservation_guest_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='reservations.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('method', models.CharField(default='cash', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reservations.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='direct', max_length=50)),
                ('rate_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='reservations.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationNight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('base_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra_guest_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_night', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_nights', to='core.hotel')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nights', to='reservations.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_nights', to='rooms.room')),
            ],
            options={
                'indexes': [models.Index(fields=['hotel', 'date'], name='reservation_hotel_i_e0caee_idx'), models.Index(fields=['room', 'date'], name='reservation_room_id_f940d8_idx')],
                'unique_together': {('reservation', 'date')},
            },
        ),
    ]
