# Generated by Django 4.2.7 on 2025-09-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_reservationcharge_payment_channelcommission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='channel',
            field=models.CharField(choices=[('direct', 'Directo'), ('booking', 'Booking'), ('expedia', 'Expedia'), ('other', 'Otro')], default='direct', max_length=20),
        ),
    ]
