# Generated by Django 4.2.7 on 2025-09-30 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0007_reservation_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('check_in', 'Check-in'), ('check_out', 'Check-out'), ('no_show', 'No-show'), ('early_check_in', 'Check-in anticipado'), ('late_check_out', 'Check-out tardío')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('check_in', 'Check-in'), ('check_out', 'Check-out'), ('no_show', 'No-show'), ('early_check_in', 'Check-in anticipado'), ('late_check_out', 'Check-out tardío')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['reservation', 'changed_at'], name='reservation_reserva_e22b11_idx'), models.Index(fields=['to_status'], name='reservation_to_stat_d7618c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReservationChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Creada'), ('updated', 'Actualizada'), ('status_changed', 'Cambio de estado'), ('check_in', 'Check-in'), ('check_out', 'Check-out'), ('cancel', 'Cancelación'), ('charge_added', 'Cargo agregado'), ('charge_removed', 'Cargo eliminado'), ('payment_added', 'Pago agregado'), ('commission_updated', 'Comisión actualizada'), ('nights_regenerated', 'Noches regeneradas')], max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('fields_changed', models.JSONField(blank=True, default=list, help_text='Campos modificados', null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot del estado anterior', null=True)),
                ('message', models.CharField(blank=True, max_length=300, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['reservation', 'changed_at'], name='reservation_reserva_5bf92b_idx'), models.Index(fields=['event_type'], name='reservation_event_t_d79789_idx')],
            },
        ),
    ]
