# Generated by Django 4.2.7 on 2025-10-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_reservationstatuschange_reservationchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='promotion_code',
            field=models.CharField(blank=True, help_text='Código de promoción aplicado', max_length=50, null=True),
        ),
    ]
