# Generated by Django 4.2.7 on 2025-10-15 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_cancellationpolicy_no_refund_message_and_more'),
        ('reservations', '0009_reservation_promotion_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='applied_cancellation_policy',
            field=models.ForeignKey(blank=True, help_text='Política de cancelación vigente al momento de crear la reserva', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.cancellationpolicy'),
        ),
    ]
