# Generated by Django 4.2.7 on 2025-10-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_add_applied_cancellation_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='applied_cancellation_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot de la política de cancelación al momento de crear la reserva', null=True),
        ),
    ]
