# Generated by Django 4.2.7 on 2025-10-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_reservation_applied_cancellation_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationchangelog',
            name='event_type',
            field=models.CharField(choices=[('created', 'Creada'), ('updated', 'Actualizada'), ('status_changed', 'Cambio de estado'), ('check_in', 'Check-in'), ('check_out', 'Check-out'), ('cancel', 'Cancelación'), ('charge_added', 'Cargo agregado'), ('charge_removed', 'Cargo eliminado'), ('payment_added', 'Pago agregado'), ('commission_updated', 'Comisión actualizada'), ('no_show_penalty', 'Penalidad NO_SHOW'), ('no_show_processed', 'NO_SHOW Procesado'), ('nights_regenerated', 'Noches regeneradas')], max_length=30),
        ),
    ]
