# Generated by Django 4.2.7 on 2025-10-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_add_no_show_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='voucher_code',
            field=models.CharField(blank=True, help_text='Código de voucher aplicado', max_length=50, null=True),
        ),
    ]
