# Generated by Django 4.2.7 on 2025-10-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_add_voucher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Número de batch del terminal', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas adicionales del pago'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='approved', help_text='Estado del pago: approved, pending_settlement, failed', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='terminal_id',
            field=models.CharField(blank=True, help_text='ID del terminal POSTNET', max_length=50),
        ),
    ]
