# Generated by Django 4.2.7 on 2025-10-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_payment_batch_number_payment_notes_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_deposit',
            field=models.BooleanField(default=False, help_text='Indica si este pago es una seña/depósito'),
        ),
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadatos adicionales del pago'),
        ),
    ]
