# Generated by Django 4.2.7 on 2025-10-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_payment_is_deposit_payment_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_pdf_url',
            field=models.URLField(blank=True, help_text='URL del comprobante PDF generado', null=True),
        ),
    ]
