# Generated by Django 4.2.7 on 2025-10-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_add_receipt_pdf_url_to_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Número de comprobante serio (ej: R-0001-000045)', max_length=20, null=True, unique=True),
        ),
    ]
