# Generated by Django 4.2.7 on 2025-10-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_payment_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Número de comprobante serio (ej: S-0001-000012 para seña, P-0001-000085 para pago)', max_length=20, null=True, unique=True),
        ),
    ]
