# Generated by Django 4.2.7 on 2025-10-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_alter_payment_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID externo de la reserva (ej: UID de iCal, ID de OTA)', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['external_id'], name='reservation_externa_ac9bf2_idx'),
        ),
    ]
