# Generated by Django 4.2.7 on 2025-11-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_reservation_external_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'permissions': []},
        ),
    ]
