# Generated by Django 4.2.7 on 2025-11-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0020_alter_reservation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='channel',
            field=models.CharField(choices=[('direct', 'Directo'), ('booking', 'Booking'), ('expedia', 'Expedia'), ('airbnb', 'Airbnb'), ('other', 'Otro')], default='direct', max_length=20),
        ),
    ]
