# Generated by Django 4.2.7 on 2025-11-04 14:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_alter_reservation_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='activation_date',
            field=models.DateField(blank=True, help_text='Fecha de activación de VCC (si aplica)', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='ARS', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='external_reference',
            field=models.CharField(blank=True, help_text='ID externo de pago/transacción OTA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_source',
            field=models.CharField(blank=True, choices=[('ota_payout', 'Payout OTA'), ('ota_vcc', 'Tarjeta virtual OTA'), ('hotel_pos', 'POS del hotel'), ('online_gateway', 'Pasarela online')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payout_date',
            field=models.DateField(blank=True, help_text='Fecha estimada/real de payout OTA', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(blank=True, help_text='Proveedor/canal (booking, airbnb, expedia)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='overbooking_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='paid_by',
            field=models.CharField(blank=True, choices=[('ota', 'Pagada por OTA'), ('hotel', 'Pago directo en hotel')], max_length=10, null=True),
        ),
    ]
