# Generated by Django 4.2.7 on 2025-11-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0022_payment_activation_date_payment_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='group_code',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador de grupo para reservas multi-habitación (misma estancia con varias habitaciones)', max_length=64, null=True),
        ),
    ]
