# Generated by Django 4.2.7 on 2025-12-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0023_reservation_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='channel',
            field=models.CharField(choices=[('direct', 'Directo'), ('whatsapp', 'WhatsApp'), ('booking', 'Booking'), ('expedia', 'Expedia'), ('airbnb', 'Airbnb'), ('other', 'Otro')], default='direct', max_length=20),
        ),
    ]
