# Generated by Django 4.2.7 on 2026-02-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0025_reservation_pricing_currency_and_price_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='channel',
            field=models.CharField(choices=[('direct', 'Directo'), ('website', 'Sitio Web'), ('whatsapp', 'WhatsApp'), ('booking', 'Booking'), ('expedia', 'Expedia'), ('airbnb', 'Airbnb'), ('other', 'Otro')], default='direct', max_length=20),
        ),
    ]
