# Generated by Django 4.2.7

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0026_alter_reservation_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                help_text='Usuario que creó la reserva (responsable)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_reservations',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
