# Generated by Django 4.2.7 on 2025-09-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('floor', models.IntegerField()),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Doble'), ('triple', 'Triple'), ('suite', 'Suite')], default='single', max_length=255)),
                ('number', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupada'), ('maintenance', 'Mantenimiento'), ('out_of_service', 'Fuera de servicio'), ('reserved', 'Reservada')], default='available', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['floor', 'name'],
                'indexes': [models.Index(fields=['room_type'], name='rooms_room_room_ty_632e38_idx'), models.Index(fields=['status'], name='rooms_room_status_19affd_idx'), models.Index(fields=['is_active'], name='rooms_room_is_acti_2e361c_idx')],
            },
        ),
    ]
