# Generated by Django 4.2.7 on 2025-11-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_extra_guest_fee_room_max_capacity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['floor', 'name'], 'permissions': [], 'verbose_name': 'Habitación', 'verbose_name_plural': 'Habitaciones'},
        ),
    ]
