# Generated by Django 4.2.7 on 2025-11-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cleaning_status',
            field=models.CharField(choices=[('dirty', 'Sucia'), ('in_progress', 'En proceso'), ('clean', 'Limpia')], default='clean', max_length=20),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['cleaning_status'], name='rooms_room_cleanin_d177b5_idx'),
        ),
    ]
