# Generated by Django 4.2.7 on 2026-01-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_backfill_room_max_capacity_from_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='Lista de URLs de imágenes adicionales de la habitación'),
        ),
        migrations.AddField(
            model_name='room',
            name='primary_image',
            field=models.ImageField(blank=True, help_text='Imagen principal de la habitación', null=True, upload_to='rooms/images/%Y/%m/%d/'),
        ),
    ]
