# Generated by Django 4.2.7 on 2026-01-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0009_room_images_room_primary_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="amenities",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de características/amenities de la habitación (strings)",
            ),
        ),
    ]

