# Generated by Cursor on 2026-02-05

from django.db import migrations, models


def seed_default_room_types(apps, schema_editor):
    RoomType = apps.get_model("rooms", "RoomType")
    defaults = [
        ("single", "Single", "Habitación individual", 0),
        ("double", "Doble", "Habitación doble", 10),
        ("triple", "Triple", "Habitación triple", 20),
        ("suite", "Suite", "Suite", 30),
    ]
    for code, name, description, sort_order in defaults:
        RoomType.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "description": description,
                "sort_order": sort_order,
                "is_active": True,
            },
        )


def unseed_default_room_types(apps, schema_editor):
    # No-op: no borramos porque pueden estar en uso.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0015_room_amenities_quantities"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(help_text="Código único (ej: single, double). Se usa en Room.room_type", max_length=50, unique=True)),
                ("name", models.CharField(help_text="Nombre visible del tipo (ej: Doble)", max_length=120)),
                ("description", models.TextField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de habitación",
                "verbose_name_plural": "Tipos de habitación",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(default="single", help_text="Código del tipo de habitación (configurable en rooms.RoomType)", max_length=50),
        ),
        migrations.AddIndex(
            model_name="roomtype",
            index=models.Index(fields=["code"], name="rooms_roomty_code_9b0b34_idx"),
        ),
        migrations.AddIndex(
            model_name="roomtype",
            index=models.Index(fields=["is_active"], name="rooms_roomty_is_acti_bfd42e_idx"),
        ),
        migrations.RunPython(seed_default_room_types, unseed_default_room_types),
    ]

