# Generated by Django 4.2.7 on 2026-02-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_roomtype_model_and_alter_room_room_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='roomtype',
            new_name='rooms_roomt_code_96a620_idx',
            old_name='rooms_roomty_code_9b0b34_idx',
        ),
        migrations.RenameIndex(
            model_name='roomtype',
            new_name='rooms_roomt_is_acti_76aa4b_idx',
            old_name='rooms_roomty_is_acti_bfd42e_idx',
        ),
    ]
