# Generated by Cursor on 2026-02-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "rooms",
            "0017_rename_rooms_roomty_code_9b0b34_idx_rooms_roomt_code_96a620_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="alias",
            field=models.CharField(
                blank=True,
                help_text="Nombre de fantasía / abreviatura (ej: OI, II). Opcional.",
                max_length=120,
                null=True,
            ),
        ),
    ]

