# Generated by Django 4.2.7 on 2025-11-11 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_alter_hotel_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0007_room_cleaning_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('zone', models.CharField(blank=True, max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_staff', to='core.hotel')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario del sistema asociado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal de limpieza',
                'verbose_name_plural': 'Personal de limpieza',
            },
        ),
        migrations.CreateModel(
            name='HousekeepingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('checkout', 'Salida'), ('daily', 'Diaria'), ('maintenance', 'Mantenimiento')], default='daily', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En proceso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('zone', models.CharField(blank=True, max_length=120, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='housekeeping.cleaningstaff')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hk_tasks', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='core.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Tarea de limpieza',
                'verbose_name_plural': 'Tareas de limpieza',
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['hotel'], name='housekeepin_hotel_i_002540_idx'), models.Index(fields=['room'], name='housekeepin_room_id_65c408_idx'), models.Index(fields=['status'], name='housekeepin_status_0b0941_idx'), models.Index(fields=['task_type'], name='housekeepin_task_ty_7aa091_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cleaningstaff',
            index=models.Index(fields=['hotel'], name='housekeepin_hotel_i_289bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningstaff',
            index=models.Index(fields=['is_active'], name='housekeepin_is_acti_776247_idx'),
        ),
    ]
