# Generated by Django 4.2.7 on 2025-11-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleaningstaff',
            options={'permissions': [('access_housekeeping', 'Puede acceder al módulo de housekeeping'), ('manage_all_tasks', 'Puede gestionar todas las tareas de housekeeping')], 'verbose_name': 'Personal de limpieza', 'verbose_name_plural': 'Personal de limpieza'},
        ),
        migrations.AlterModelOptions(
            name='housekeepingtask',
            options={'ordering': ['-priority', 'created_at'], 'permissions': [('access_housekeeping', 'Puede acceder al módulo de housekeeping'), ('manage_all_tasks', 'Puede gestionar todas las tareas de housekeeping')], 'verbose_name': 'Tarea de limpieza', 'verbose_name_plural': 'Tareas de limpieza'},
        ),
    ]
