# Generated by Django 4.2.7 on 2025-11-11 17:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_hotel_options'),
        ('housekeeping', '0002_alter_cleaningstaff_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_auto_assign', models.BooleanField(default=True)),
                ('create_daily_tasks', models.BooleanField(default=True)),
                ('daily_generation_time', models.TimeField(default=datetime.time(7, 0))),
                ('skip_service_on_checkin', models.BooleanField(default=True)),
                ('skip_service_on_checkout', models.BooleanField(default=True)),
                ('linens_every_n_nights', models.PositiveIntegerField(default=3)),
                ('towels_every_n_nights', models.PositiveIntegerField(default=1)),
                ('morning_window_start', models.TimeField(blank=True, default=datetime.time(9, 0), null=True)),
                ('morning_window_end', models.TimeField(blank=True, default=datetime.time(13, 0), null=True)),
                ('afternoon_window_start', models.TimeField(blank=True, default=datetime.time(13, 0), null=True)),
                ('afternoon_window_end', models.TimeField(blank=True, default=datetime.time(18, 0), null=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('prefer_by_zone', models.BooleanField(default=True)),
                ('rebalance_every_minutes', models.PositiveIntegerField(default=5)),
                ('checkout_priority', models.PositiveIntegerField(default=2)),
                ('daily_priority', models.PositiveIntegerField(default=1)),
                ('durations', models.JSONField(blank=True, default=dict)),
                ('alert_checkout_unstarted_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_config', to='core.hotel')),
            ],
            options={
                'verbose_name': 'Configuración de Housekeeping',
                'verbose_name_plural': 'Configuraciones de Housekeeping',
                'indexes': [models.Index(fields=['hotel'], name='housekeepin_hotel_i_d8d551_idx')],
            },
        ),
    ]
