# Generated by Django 4.2.7 on 2025-11-24 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_hotel_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('housekeeping', '0003_housekeepingconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del checklist', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('room_type', models.CharField(blank=True, help_text='Tipo de habitación específico (opcional)', max_length=20, null=True)),
                ('task_type', models.CharField(blank=True, choices=[('checkout', 'Salida'), ('daily', 'Diaria'), ('maintenance', 'Mantenimiento')], help_text='Tipo de tarea específico (opcional)', max_length=20, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Checklist por defecto para el hotel')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='core.hotel')),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del item', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición')),
                ('is_required', models.BooleanField(default=True, help_text='Si es requerido o opcional')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='housekeeping.checklist')),
            ],
            options={
                'verbose_name': 'Item de Checklist',
                'verbose_name_plural': 'Items de Checklist',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='cleaningstaff',
            name='shift',
            field=models.CharField(blank=True, choices=[('morning', 'Mañana'), ('afternoon', 'Tarde'), ('night', 'Noche')], help_text='Turno de trabajo (mañana, tarde, noche)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cleaningstaff',
            name='zone',
            field=models.CharField(blank=True, help_text='Zona libre (legacy, usar cleaning_zones)', max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='CleaningZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la zona (ej: Piso 1, Ala A)', max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, help_text='Piso (opcional)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_zones', to='core.hotel')),
            ],
            options={
                'verbose_name': 'Zona de Limpieza',
                'verbose_name_plural': 'Zonas de Limpieza',
            },
        ),
        migrations.AddField(
            model_name='cleaningstaff',
            name='cleaning_zones',
            field=models.ManyToManyField(blank=True, help_text='Zonas asignadas a este empleado', related_name='staff', to='housekeeping.cleaningzone'),
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(help_text='Tipo de habitación (single, double, triple, suite)', max_length=20)),
                ('task_type', models.CharField(choices=[('checkout', 'Salida'), ('daily', 'Diaria'), ('maintenance', 'Mantenimiento')], default='daily', max_length=20)),
                ('name', models.CharField(help_text='Nombre de la tarea (ej: Cambio de sábanas, Reposición minibar)', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('estimated_minutes', models.PositiveIntegerField(default=15, help_text='Duración estimada en minutos')),
                ('is_required', models.BooleanField(default=True, help_text='Si es requerida o opcional')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de ejecución')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='core.hotel')),
            ],
            options={
                'verbose_name': 'Plantilla de Tarea',
                'verbose_name_plural': 'Plantillas de Tareas',
                'ordering': ['room_type', 'task_type', 'order'],
                'indexes': [models.Index(fields=['hotel'], name='housekeepin_hotel_i_52aa5c_idx'), models.Index(fields=['room_type'], name='housekeepin_room_ty_6c058b_idx'), models.Index(fields=['task_type'], name='housekeepin_task_ty_2ac92d_idx'), models.Index(fields=['is_active'], name='housekeepin_is_acti_94ca38_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskChecklistCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='housekeeping.checklistitem')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_completions', to='housekeeping.housekeepingtask')),
            ],
            options={
                'verbose_name': 'Completado de Item de Checklist',
                'verbose_name_plural': 'Completados de Items de Checklist',
                'indexes': [models.Index(fields=['task'], name='housekeepin_task_id_7363b8_idx'), models.Index(fields=['checklist_item'], name='housekeepin_checkli_06ed80_idx'), models.Index(fields=['completed'], name='housekeepin_complet_1dcb4a_idx')],
                'unique_together': {('task', 'checklist_item')},
            },
        ),
        migrations.AddIndex(
            model_name='cleaningzone',
            index=models.Index(fields=['hotel'], name='housekeepin_hotel_i_ecbb76_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningzone',
            index=models.Index(fields=['is_active'], name='housekeepin_is_acti_992612_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cleaningzone',
            unique_together={('hotel', 'name')},
        ),
        migrations.AddIndex(
            model_name='checklistitem',
            index=models.Index(fields=['checklist'], name='housekeepin_checkli_87eced_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistitem',
            index=models.Index(fields=['is_active'], name='housekeepin_is_acti_ab5ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['hotel'], name='housekeepin_hotel_i_e5c3d0_idx'),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['room_type'], name='housekeepin_room_ty_be7520_idx'),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['task_type'], name='housekeepin_task_ty_445ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='checklist',
            index=models.Index(fields=['is_active'], name='housekeepin_is_acti_4fc6d2_idx'),
        ),
    ]
