# Generated by Django 4.2.7 on 2025-11-24 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0004_checklist_checklistitem_cleaningstaff_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeepingtask',
            name='checklist',
            field=models.ForeignKey(blank=True, help_text='Checklist asociado a esta tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='housekeeping.checklist'),
        ),
    ]
