# Generated by Django 4.2.7 on 2025-11-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0005_housekeepingtask_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningstaff',
            name='work_end_time',
            field=models.TimeField(blank=True, help_text='Hora de fin del turno de trabajo (ej: 17:00)', null=True),
        ),
        migrations.AddField(
            model_name='cleaningstaff',
            name='work_start_time',
            field=models.TimeField(blank=True, help_text='Hora de inicio del turno de trabajo (ej: 09:00)', null=True),
        ),
    ]
