# Generated by Django 4.2.7 on 2025-11-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0006_add_work_hours_to_cleaning_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeepingconfig',
            name='auto_complete_overdue',
            field=models.BooleanField(default=False, help_text='Si está activo, completa automáticamente las tareas vencidas después del tiempo máximo'),
        ),
        migrations.AddField(
            model_name='housekeepingconfig',
            name='max_task_duration_minutes',
            field=models.PositiveIntegerField(default=120, help_text='Tiempo máximo en minutos para una tarea en progreso antes de marcarla como vencida'),
        ),
        migrations.AddField(
            model_name='housekeepingconfig',
            name='overdue_grace_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Minutos adicionales después del tiempo máximo antes de auto-completar (solo si auto_complete_overdue está activo)'),
        ),
        migrations.AddField(
            model_name='housekeepingtask',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Duración estimada en minutos (se calcula desde templates o configuración)', null=True),
        ),
        migrations.AddField(
            model_name='housekeepingtask',
            name='is_overdue',
            field=models.BooleanField(default=False, help_text='Indica si la tarea está vencida (excedió su tiempo estimado)'),
        ),
    ]
