services:
  - type: web
    name: alojasys-backend
    env: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: USE_SQLITE
        value: "True"
    healthCheckPath: /health/

  - type: web
    name: alojasys-frontend
    env: static
    rootDir: frontend
    installCommand: npm ci --no-audit --no-fund || npm install --no-audit --no-fund
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: "20"


databases:
  - name: alojasys-db
    plan: free
