# Generated by Django 4.2.7 on 2025-10-17 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('auto_cancel', 'Auto Cancelación'), ('no_show', 'No Show'), ('refund_auto', 'Reembolso Automático'), ('refund_failed', 'Reembolso Fallido')], help_text='Tipo de notificación', max_length=20)),
                ('title', models.CharField(help_text='Título de la notificación', max_length=200)),
                ('message', models.TextField(help_text='Mensaje detallado de la notificación')),
                ('is_read', models.BooleanField(default=False, help_text='Indica si la notificación ha sido leída')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('hotel_id', models.PositiveIntegerField(blank=True, help_text='ID del hotel relacionado', null=True)),
                ('reservation_id', models.PositiveIntegerField(blank=True, help_text='ID de la reserva relacionada', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario destinatario (null = todos los usuarios)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['type', 'created_at'], name='notificatio_type_8e213d_idx'), models.Index(fields=['hotel_id', 'created_at'], name='notificatio_hotel_i_e35c83_idx')],
            },
        ),
    ]
