# Generated by Django 4.2.7 on 2025-10-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('auto_cancel', 'Auto Cancelación'), ('manual_cancel', 'Cancelación Manual'), ('no_show', 'No Show'), ('refund_auto', 'Reembolso Automático'), ('refund_failed', 'Reembolso Fallido'), ('receipt_generated', 'Comprobante Generado')], help_text='Tipo de notificación', max_length=20),
        ),
    ]
