# Generated by Django 4.2.7 on 2025-11-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('auto_cancel', 'Auto Cancelación'), ('manual_cancel', 'Cancelación Manual'), ('no_show', 'No Show'), ('refund_auto', 'Reembolso Automático'), ('refund_failed', 'Reembolso Fallido'), ('receipt_generated', 'Comprobante Generado'), ('ota_reservation_received', 'Nueva Reserva OTA'), ('housekeeping_task_created', 'Tarea de Limpieza Creada')], help_text='Tipo de notificación', max_length=30),
        ),
    ]
