# Generated by Django 4.2.7 on 2025-09-30 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_hotel_enterprise_delete_enterprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('available_rooms', models.PositiveIntegerField(default=0)),
                ('occupied_rooms', models.PositiveIntegerField(default=0)),
                ('maintenance_rooms', models.PositiveIntegerField(default=0)),
                ('out_of_service_rooms', models.PositiveIntegerField(default=0)),
                ('reserved_rooms', models.PositiveIntegerField(default=0)),
                ('total_reservations', models.PositiveIntegerField(default=0)),
                ('pending_reservations', models.PositiveIntegerField(default=0)),
                ('confirmed_reservations', models.PositiveIntegerField(default=0)),
                ('cancelled_reservations', models.PositiveIntegerField(default=0)),
                ('check_in_today', models.PositiveIntegerField(default=0)),
                ('check_out_today', models.PositiveIntegerField(default=0)),
                ('no_show_today', models.PositiveIntegerField(default=0)),
                ('total_guests', models.PositiveIntegerField(default=0)),
                ('guests_checked_in', models.PositiveIntegerField(default=0)),
                ('guests_expected_today', models.PositiveIntegerField(default=0)),
                ('guests_departing_today', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_room_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('occupancy_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('single_rooms_occupied', models.PositiveIntegerField(default=0)),
                ('double_rooms_occupied', models.PositiveIntegerField(default=0)),
                ('triple_rooms_occupied', models.PositiveIntegerField(default=0)),
                ('suite_rooms_occupied', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_metrics', to='core.hotel')),
            ],
            options={
                'verbose_name': 'Métrica del Dashboard',
                'verbose_name_plural': 'Métricas del Dashboard',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['hotel', 'date'], name='dashboard_d_hotel_i_fbe5cb_idx'), models.Index(fields=['date'], name='dashboard_d_date_21e182_idx')],
                'unique_together': {('hotel', 'date')},
            },
        ),
    ]
