# Generated by Django 4.2.7 on 2025-09-30 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
    ]
