# Generated by Django 4.2.7 on 2025-10-22 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0006_state_sync_meta'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enterprise',
            field=models.ForeignKey(blank=True, help_text='Empresa principal del usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='enterprises.enterprise'),
        ),
    ]
