# Generated by Django 4.2.7 on 2025-10-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_image',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='users/avatars/%Y/%m/%d/'),
        ),
    ]
