# Generated by Django 4.2.7 on 2025-11-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_avatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_housekeeping_staff',
            field=models.BooleanField(default=False, help_text='Si está activo, el usuario es staff de limpieza con acceso limitado al módulo de housekeeping.'),
        ),
    ]
