# Generated by Django 4.2.7 on 2025-09-20 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_hotel_country_alter_hotel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='check_in_time',
            field=models.TimeField(default=datetime.time(15, 0)),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_out_time',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
    ]
