# Generated by Django 4.2.7 on 2025-09-25 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_city_postal_code'),
        ('core', '0003_hotel_check_in_time_hotel_check_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hotels', to='locations.country'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hotels', to='locations.state'),
        ),
    ]
