# Generated by Django 4.2.7 on 2025-09-26 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
        ('core', '0005_enterprise_hotel_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hotels', to='enterprises.enterprise'),
        ),
        migrations.DeleteModel(
            name='Enterprise',
        ),
    ]
