# Generated by Django 4.2.7 on 2025-10-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_hotel_enterprise_delete_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='auto_check_in_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
