# Generated by Django 4.2.7 on 2025-10-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hotel_auto_check_in_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='auto_no_show_enabled',
            field=models.BooleanField(default=False, help_text='Habilita el marcado automático de reservas como no-show'),
        ),
    ]
