# Generated by Django 4.2.7 on 2025-10-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_hotel_auto_no_show_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo del hotel', null=True, upload_to='hotels/logos/%Y/%m/%d/'),
        ),
    ]
