# Generated by Django 4.2.7 on 2025-11-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_hotel_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='auto_check_out_enabled',
            field=models.BooleanField(default=True, help_text='Habilita el check-out automático de reservas'),
        ),
    ]
