# Generated by Django 4.2.7 on 2025-11-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_auto_check_out_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'permissions': [], 'verbose_name': 'Hotel', 'verbose_name_plural': 'Hoteles'},
        ),
    ]
