# Generated by Django 4.2.7 on 2025-11-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_hotel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False, help_text='Habilita la captura automática de reservas vía WhatsApp'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='whatsapp_phone',
            field=models.CharField(blank=True, help_text='Número oficial de WhatsApp del hotel (formato E.164)', max_length=30),
        ),
    ]
