# Generated by Django 4.2.7 on 2025-11-28 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatbotprovideraccount'),
        ('core', '0012_hotel_whatsapp_enabled_hotel_whatsapp_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='whatsapp_api_token',
            field=models.CharField(blank=True, help_text='Token/API Key del proveedor (almacenamiento básico, considerar cifrado)', max_length=512),
        ),
        migrations.AddField(
            model_name='hotel',
            name='whatsapp_business_id',
            field=models.CharField(blank=True, help_text='Business ID (Meta) u otro identificador requerido por el proveedor', max_length=64),
        ),
        migrations.AddField(
            model_name='hotel',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, help_text='Phone Number ID (Meta) u otro ID interno del número', max_length=64),
        ),
        migrations.AddField(
            model_name='hotel',
            name='whatsapp_provider',
            field=models.CharField(blank=True, choices=[('meta_cloud', 'Meta WhatsApp Cloud API'), ('twilio', 'Twilio'), ('other', 'Otro')], help_text='Proveedor directo si el hotel trae su propia cuenta', max_length=30),
        ),
        migrations.AddField(
            model_name='hotel',
            name='whatsapp_provider_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta administrada por AlojaSys para usar un número compartido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='chatbot.chatbotprovideraccount'),
        ),
    ]
