# Generated by Django 4.2.7 on 2026-01-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_hotel_whatsapp_api_token_hotel_whatsapp_business_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='guest_card_policies',
            field=models.TextField(blank=True, help_text='Políticas y horarios que aparecen en la ficha del pasajero (texto libre, se imprime al final de la ficha)', null=True),
        ),
    ]
