# Generated by Django 4.2.7 on 2025-12-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0006_state_sync_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='enabled_features',
            field=models.JSONField(blank=True, default=dict, help_text='Overrides de funcionalidades por empresa. Se combinan con los defaults del plan para habilitar/deshabilitar módulos.'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='plan_type',
            field=models.CharField(choices=[('basic', 'Básico'), ('medium', 'Medio'), ('full', 'Full'), ('custom', 'Custom')], default='basic', help_text='Plan comercial contratado que determina el conjunto base de funcionalidades.', max_length=20),
        ),
    ]
