# Generated by Django 4.2.7 on 2025-10-14 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0005_room_extra_guest_fee_room_max_capacity_and_more'),
        ('core', '0007_hotel_auto_check_in_enabled'),
        ('reservations', '0009_reservation_promotion_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_view', models.CharField(choices=[('month', 'Mes'), ('week', 'Semana'), ('day', 'Día'), ('rooms', 'Habitaciones')], default='month', max_length=20)),
                ('show_maintenance', models.BooleanField(default=True)),
                ('show_blocks', models.BooleanField(default=True)),
                ('show_revenue', models.BooleanField(default=False)),
                ('room_types', models.JSONField(blank=True, default=list)),
                ('floors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_views', to='core.hotel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_view', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vista de Calendario',
                'verbose_name_plural': 'Vistas de Calendario',
            },
        ),
        migrations.CreateModel(
            name='RoomMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('maintenance_type', models.CharField(choices=[('cleaning', 'Limpieza'), ('maintenance', 'Mantenimiento'), ('repair', 'Reparación'), ('inspection', 'Inspección'), ('deep_cleaning', 'Limpieza Profunda')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_maintenance', to='core.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Mantenimiento de Habitación',
                'verbose_name_plural': 'Mantenimientos de Habitaciones',
                'ordering': ['start_date', 'priority'],
                'indexes': [models.Index(fields=['hotel', 'start_date'], name='calendar_ro_hotel_i_0c90af_idx'), models.Index(fields=['room', 'start_date'], name='calendar_ro_room_id_28d14e_idx'), models.Index(fields=['status'], name='calendar_ro_status_50dca8_idx'), models.Index(fields=['priority'], name='calendar_ro_priorit_bffc62_idx')],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('reservation', 'Reserva'), ('maintenance', 'Mantenimiento'), ('block', 'Bloqueo'), ('cleaning', 'Limpieza'), ('out_of_service', 'Fuera de Servicio')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_all_day', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.hotel')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='reservations.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Evento de Calendario',
                'verbose_name_plural': 'Eventos de Calendario',
                'ordering': ['start_date', 'room__name'],
                'indexes': [models.Index(fields=['hotel', 'start_date'], name='calendar_ca_hotel_i_47cb0b_idx'), models.Index(fields=['room', 'start_date'], name='calendar_ca_room_id_bc4f0d_idx'), models.Index(fields=['event_type'], name='calendar_ca_event_t_7fae4a_idx'), models.Index(fields=['is_active'], name='calendar_ca_is_acti_ecef9a_idx')],
            },
        ),
    ]
