# Generated by Django 4.2.7 on 2025-10-04 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_hotel_enterprise_delete_enterprise'),
        ('rooms', '0005_room_extra_guest_fee_room_max_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(help_text='Código interno/para canal', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Mayor = más prioridad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='core.hotel')),
            ],
            options={
                'ordering': ['-is_active', '-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('apply_mon', models.BooleanField(default=True)),
                ('apply_tue', models.BooleanField(default=True)),
                ('apply_wed', models.BooleanField(default=True)),
                ('apply_thu', models.BooleanField(default=True)),
                ('apply_fri', models.BooleanField(default=True)),
                ('apply_sat', models.BooleanField(default=True)),
                ('apply_sun', models.BooleanField(default=True)),
                ('target_room_type', models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Doble'), ('triple', 'Triple'), ('suite', 'Suite')], max_length=30, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('price_mode', models.CharField(choices=[('absolute', 'Absoluto'), ('delta', 'Delta sobre la tarifa base')], default='absolute', max_length=10)),
                ('base_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('extra_guest_fee_amount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Extra por huésped por encima de la capacidad incluida (opcional).', max_digits=10, null=True)),
                ('min_stay', models.PositiveIntegerField(blank=True, default=1, help_text='Mínimo de noches para aplicar la regla (opcional).', null=True)),
                ('max_stay', models.PositiveIntegerField(blank=True, default=None, help_text='Máximo de noches para aplicar la regla (opcional).', null=True)),
                ('closed', models.BooleanField(default=False)),
                ('closed_to_arrival', models.BooleanField(default=False)),
                ('closed_to_departure', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='rates.rateplan')),
                ('target_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_rules', to='rooms.room')),
            ],
            options={
                'ordering': ['-priority', 'start_date', 'end_date'],
            },
        ),
        migrations.CreateModel(
            name='RateOccupancyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy', models.PositiveIntegerField(default=1, help_text='Número de huéspedes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_prices', to='rates.raterule')),
            ],
            options={
                'ordering': ['occupancy'],
            },
        ),
        migrations.AddIndex(
            model_name='raterule',
            index=models.Index(fields=['start_date', 'end_date'], name='rates_rater_start_d_4a0368_idx'),
        ),
        migrations.AddIndex(
            model_name='raterule',
            index=models.Index(fields=['priority'], name='rates_rater_priorit_591e17_idx'),
        ),
        migrations.AddIndex(
            model_name='raterule',
            index=models.Index(fields=['channel'], name='rates_rater_channel_615bd7_idx'),
        ),
        migrations.AddConstraint(
            model_name='rateplan',
            constraint=models.UniqueConstraint(fields=('hotel', 'code'), name='uniq_rateplan_hotel_code'),
        ),
        migrations.AlterUniqueTogether(
            name='rateoccupancyprice',
            unique_together={('rule', 'occupancy')},
        ),
    ]
