# Generated by Django 4.2.7 on 2025-10-04 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_hotel_enterprise_delete_enterprise'),
        ('rooms', '0005_room_extra_guest_fee_room_max_capacity_and_more'),
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('percent', models.DecimalField(decimal_places=2, default=0, help_text='% aplicado sobre (base + extra - descuento)', max_digits=6)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='core.hotel')),
            ],
            options={
                'ordering': ['-is_active', '-priority', 'name'],
                'indexes': [models.Index(fields=['hotel'], name='rates_taxru_hotel_i_37dc74_idx'), models.Index(fields=['priority'], name='rates_taxru_priorit_6fc044_idx')],
            },
        ),
        migrations.CreateModel(
            name='PromoRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, help_text='Código promocional (opcional)', max_length=40, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('apply_mon', models.BooleanField(default=True)),
                ('apply_tue', models.BooleanField(default=True)),
                ('apply_wed', models.BooleanField(default=True)),
                ('apply_thu', models.BooleanField(default=True)),
                ('apply_fri', models.BooleanField(default=True)),
                ('apply_sat', models.BooleanField(default=True)),
                ('apply_sun', models.BooleanField(default=True)),
                ('target_room_type', models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Doble'), ('triple', 'Triple'), ('suite', 'Suite')], max_length=30, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('discount_type', models.CharField(choices=[('percent', 'Porcentaje'), ('fixed', 'Monto fijo')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('combinable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_rules', to='core.hotel')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_rules', to='rates.rateplan')),
                ('target_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_rules', to='rooms.room')),
            ],
            options={
                'ordering': ['-is_active', '-priority', 'start_date', 'end_date'],
                'indexes': [models.Index(fields=['hotel', 'start_date', 'end_date'], name='rates_promo_hotel_i_309af1_idx'), models.Index(fields=['priority'], name='rates_promo_priorit_ddb593_idx'), models.Index(fields=['code'], name='rates_promo_code_a44af6_idx')],
            },
        ),
    ]
