# Generated by Django 4.2.7 on 2025-10-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_taxrule_promorule'),
    ]

    operations = [
        migrations.AddField(
            model_name='promorule',
            name='scope',
            field=models.CharField(choices=[('per_night', 'Por noche'), ('per_reservation', 'Por reserva')], default='per_night', max_length=20),
        ),
    ]
