# Generated by Django 4.2.7 on 2025-10-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_promorule_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrule',
            name='amount_type',
            field=models.CharField(choices=[('percent', 'Porcentaje'), ('fixed', 'Monto fijo')], default='percent', max_length=10),
        ),
        migrations.AddField(
            model_name='taxrule',
            name='fixed_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo (si corresponde)', max_digits=10),
        ),
        migrations.AddField(
            model_name='taxrule',
            name='scope',
            field=models.CharField(choices=[('per_night', 'Por noche'), ('per_reservation', 'Por reserva'), ('per_guest_per_night', 'Por huésped por noche')], default='per_night', max_length=30),
        ),
    ]
