# Generated by Django 4.2.7 on 2025-10-09 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentmethod_paymentpolicy_and_more'),
        ('rates', '0005_raterule_deposit_days_before_raterule_deposit_due_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raterule',
            name='deposit_days_before',
        ),
        migrations.RemoveField(
            model_name='raterule',
            name='deposit_due',
        ),
        migrations.RemoveField(
            model_name='raterule',
            name='deposit_type',
        ),
        migrations.RemoveField(
            model_name='raterule',
            name='deposit_value',
        ),
        migrations.AddField(
            model_name='raterule',
            name='payment_policy',
            field=models.ForeignKey(blank=True, help_text='Política de pago específica para esta regla (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentpolicy'),
        ),
    ]
