# Generated by Django 4.2.7 on 2025-10-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0006_remove_raterule_deposit_days_before_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raterule',
            name='payment_policy',
        ),
        migrations.AddField(
            model_name='raterule',
            name='deposit_days_before',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Solo si deposit_due = days_before', null=True),
        ),
        migrations.AddField(
            model_name='raterule',
            name='deposit_due',
            field=models.CharField(choices=[('confirmation', 'Al confirmar'), ('days_before', 'Días antes del check-in'), ('check_in', 'Al check-in')], default='confirmation', help_text='Cuándo vence el pago del adelanto', max_length=20),
        ),
        migrations.AddField(
            model_name='raterule',
            name='deposit_type',
            field=models.CharField(choices=[('none', 'Sin adelanto'), ('percentage', 'Porcentaje del total'), ('fixed', 'Monto fijo')], default='none', help_text='Tipo de adelanto requerido por esta regla', max_length=20),
        ),
        migrations.AddField(
            model_name='raterule',
            name='deposit_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
