# Generated by Cursor on 2026-02-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0007_remove_raterule_payment_policy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raterule",
            name="target_room_type",
            field=models.CharField(blank=True, help_text="Código de tipo de habitación (rooms.RoomType.code)", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="promorule",
            name="target_room_type",
            field=models.CharField(blank=True, help_text="Código de tipo de habitación (rooms.RoomType.code)", max_length=50, null=True),
        ),
    ]

