# Generated by Django 4.2.7 on 2026-02-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cashmovement',
            new_name='cashbox_cas_hotel_i_ba57fb_idx',
            old_name='cashbox_cas_hotel_i_62d2c6_idx',
        ),
        migrations.RenameIndex(
            model_name='cashmovement',
            new_name='cashbox_cas_session_b25721_idx',
            old_name='cashbox_cas_session_2a3c4e_idx',
        ),
        migrations.RenameIndex(
            model_name='cashmovement',
            new_name='cashbox_cas_hotel_i_9e89b1_idx',
            old_name='cashbox_cas_hotel_i_92f3a3_idx',
        ),
        migrations.RenameIndex(
            model_name='cashsession',
            new_name='cashbox_cas_hotel_i_4b75ff_idx',
            old_name='cashbox_cas_hotel_i_9e4e0c_idx',
        ),
        migrations.RenameIndex(
            model_name='cashsession',
            new_name='cashbox_cas_hotel_i_dfe36f_idx',
            old_name='cashbox_cas_hotel_i_60d8a7_idx',
        ),
        migrations.RenameIndex(
            model_name='cashsession',
            new_name='cashbox_cas_hotel_i_2674e2_idx',
            old_name='cashbox_cas_hotel_i_3ee05f_idx',
        ),
    ]
