# Generated by Django 4.2.7 on 2025-10-29 19:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0005_room_extra_guest_fee_room_max_capacity_and_more'),
        ('core', '0009_hotel_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtaSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ical', 'iCal'), ('booking', 'Booking'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('other', 'Otro')], max_length=20)),
                ('job_type', models.CharField(choices=[('import_ics', 'Import ICS'), ('export_ics', 'Export ICS'), ('push_ari', 'Push ARI'), ('pull_reservations', 'Pull Reservations')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ota_sync_jobs', to='core.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='OtaRoomMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ical', 'iCal'), ('booking', 'Booking'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('other', 'Otro')], max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=120, null=True)),
                ('ical_in_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_room_mappings', to='core.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_mappings', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='OtaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ical', 'iCal'), ('booking', 'Booking'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('other', 'Otro')], max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, max_length=120, null=True)),
                ('ical_out_token', models.CharField(blank=True, max_length=64, null=True)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_configs', to='core.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='OtaSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='otas.otasyncjob')),
            ],
            options={
                'indexes': [models.Index(fields=['level', 'created_at'], name='otas_otasyn_level_698fa3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='otasyncjob',
            index=models.Index(fields=['provider', 'job_type', 'status'], name='otas_otasyn_provide_546897_idx'),
        ),
        migrations.AddIndex(
            model_name='otasyncjob',
            index=models.Index(fields=['started_at'], name='otas_otasyn_started_3b824c_idx'),
        ),
        migrations.AddIndex(
            model_name='otaroommapping',
            index=models.Index(fields=['hotel', 'provider'], name='otas_otaroo_hotel_i_dab071_idx'),
        ),
        migrations.AddIndex(
            model_name='otaroommapping',
            index=models.Index(fields=['room', 'provider'], name='otas_otaroo_room_id_dcd4e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='otaroommapping',
            unique_together={('room', 'provider')},
        ),
        migrations.AddIndex(
            model_name='otaconfig',
            index=models.Index(fields=['hotel', 'provider'], name='otas_otacon_hotel_i_a12e01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='otaconfig',
            unique_together={('hotel', 'provider')},
        ),
    ]
