# Generated by Django 4.2.7 on 2025-10-30 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_extra_guest_fee_room_max_capacity_and_more'),
        ('core', '0009_hotel_logo'),
        ('otas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtaImportedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ical', 'iCal'), ('booking', 'Booking'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('other', 'Otro')], default='ical', max_length=20)),
                ('uid', models.CharField(max_length=255)),
                ('dtstart', models.DateField()),
                ('dtend', models.DateField()),
                ('source_url', models.URLField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_imported_events', to='core.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_imported_events', to='rooms.room')),
            ],
            options={
                'indexes': [models.Index(fields=['hotel', 'room'], name='otas_otaimp_hotel_i_c5fc74_idx'), models.Index(fields=['provider'], name='otas_otaimp_provide_15e793_idx')],
                'unique_together': {('room', 'provider', 'uid')},
            },
        ),
    ]
