# Generated by Django 4.2.7 on 2025-10-30 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_hotel_logo'),
        ('otas', '0002_otaimportedevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtaRoomTypeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ical', 'iCal'), ('booking', 'Booking'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('other', 'Otro')], max_length=20)),
                ('room_type_code', models.CharField(help_text='Código interno del PMS (ej: DOUBLE)', max_length=60)),
                ('provider_code', models.CharField(help_text='Código en la OTA', max_length=120)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_room_type_mappings', to='core.hotel')),
            ],
            options={
                'indexes': [models.Index(fields=['hotel', 'provider'], name='otas_otaroo_hotel_i_fa6698_idx')],
                'unique_together': {('hotel', 'provider', 'room_type_code')},
            },
        ),
        migrations.CreateModel(
            name='OtaRatePlanMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ical', 'iCal'), ('booking', 'Booking'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('other', 'Otro')], max_length=20)),
                ('rate_plan_code', models.CharField(help_text='Código interno PMS (ej: STANDARD)', max_length=60)),
                ('provider_code', models.CharField(help_text='Código en la OTA', max_length=120)),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_rate_plan_mappings', to='core.hotel')),
            ],
            options={
                'indexes': [models.Index(fields=['hotel', 'provider'], name='otas_otarat_hotel_i_641701_idx')],
                'unique_together': {('hotel', 'provider', 'rate_plan_code')},
            },
        ),
    ]
