# Generated by Django 4.2.7 on 2025-10-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otas', '0003_otaroomtypemapping_otarateplanmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='otaconfig',
            name='booking_base_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otaconfig',
            name='booking_client_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='otaconfig',
            name='booking_client_secret',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='otaconfig',
            name='booking_hotel_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='otaconfig',
            name='booking_mode',
            field=models.CharField(choices=[('test', 'Test'), ('prod', 'Prod')], default='test', max_length=8),
        ),
    ]
