# Generated by Django 4.2.7 on 2025-10-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otas', '0004_otaconfig_booking_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otaconfig',
            name='airbnb_account_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='otaconfig',
            name='airbnb_base_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otaconfig',
            name='airbnb_client_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='otaconfig',
            name='airbnb_client_secret',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='otaconfig',
            name='airbnb_mode',
            field=models.CharField(choices=[('test', 'Test'), ('prod', 'Prod')], default='test', max_length=8),
        ),
    ]
