# Generated by Django 4.2.7 on 2025-10-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otas', '0005_otaconfig_airbnb_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otaroommapping',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otaroommapping',
            name='sync_direction',
            field=models.CharField(choices=[('import', 'Import'), ('export', 'Export'), ('both', 'Both')], default='both', max_length=10),
        ),
    ]
