# Generated by Django 4.2.7 on 2025-10-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otas', '0006_otaroommapping_last_synced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otaconfig',
            name='verified',
            field=models.BooleanField(default=False, help_text='Indica si la configuración base_url es válida y está verificada'),
        ),
    ]
