# Generated by Django 4.2.7 on 2025-11-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otas', '0007_add_verified_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='otaroommapping',
            name='google_resource_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='otaroommapping',
            name='google_sync_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otaroommapping',
            name='google_watch_channel_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='otaroommapping',
            name='google_watch_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otaroommapping',
            name='google_webhook_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='otaconfig',
            name='provider',
            field=models.CharField(choices=[('ical', 'iCal'), ('booking', 'Booking'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('google', 'Google Calendar'), ('other', 'Otro')], max_length=255),
        ),
        migrations.AlterField(
            model_name='otaimportedevent',
            name='provider',
            field=models.CharField(choices=[('ical', 'iCal'), ('booking', 'Booking'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('google', 'Google Calendar'), ('other', 'Otro')], default='ical', max_length=20),
        ),
        migrations.AlterField(
            model_name='otarateplanmapping',
            name='provider',
            field=models.CharField(choices=[('ical', 'iCal'), ('booking', 'Booking'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('google', 'Google Calendar'), ('other', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='otaroommapping',
            name='provider',
            field=models.CharField(choices=[('ical', 'iCal'), ('booking', 'Booking'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('google', 'Google Calendar'), ('other', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='otaroomtypemapping',
            name='provider',
            field=models.CharField(choices=[('ical', 'iCal'), ('booking', 'Booking'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('google', 'Google Calendar'), ('other', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='otasyncjob',
            name='provider',
            field=models.CharField(choices=[('ical', 'iCal'), ('booking', 'Booking'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('google', 'Google Calendar'), ('other', 'Otro')], max_length=20),
        ),
    ]
