# Generated by Django 4.2.7 on 2026-01-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otas', '0008_otaroommapping_google_resource_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otaconfig',
            name='provider',
            field=models.CharField(choices=[('ical', 'iCal'), ('booking', 'Booking'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('smoobu', 'Smoobu'), ('google', 'Google Calendar'), ('other', 'Otro')], max_length=255),
        ),
        migrations.AlterField(
            model_name='otaimportedevent',
            name='provider',
            field=models.CharField(choices=[('ical', 'iCal'), ('booking', 'Booking'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('smoobu', 'Smoobu'), ('google', 'Google Calendar'), ('other', 'Otro')], default='ical', max_length=20),
        ),
        migrations.AlterField(
            model_name='otarateplanmapping',
            name='provider',
            field=models.CharField(choices=[('ical', 'iCal'), ('booking', 'Booking'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('smoobu', 'Smoobu'), ('google', 'Google Calendar'), ('other', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='otaroommapping',
            name='provider',
            field=models.CharField(choices=[('ical', 'iCal'), ('booking', 'Booking'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('smoobu', 'Smoobu'), ('google', 'Google Calendar'), ('other', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='otaroomtypemapping',
            name='provider',
            field=models.CharField(choices=[('ical', 'iCal'), ('booking', 'Booking'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('smoobu', 'Smoobu'), ('google', 'Google Calendar'), ('other', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='otasyncjob',
            name='provider',
            field=models.CharField(choices=[('ical', 'iCal'), ('booking', 'Booking'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('smoobu', 'Smoobu'), ('google', 'Google Calendar'), ('other', 'Otro')], max_length=20),
        ),
    ]
