# Generated by Django 4.2.7 on 2026-01-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otas', '0010_smoobu_exported_booking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='smoobuexportedbooking',
            new_name='otas_smoobu_hotel_i_2fc39c_idx',
            old_name='otas_smoobu_hotel_room_kind_idx',
        ),
        migrations.RenameIndex(
            model_name='smoobuexportedbooking',
            new_name='otas_smoobu_smoobu__74f41a_idx',
            old_name='otas_smoobu_booking_id_idx',
        ),
        migrations.RenameIndex(
            model_name='smoobuexportedbooking',
            new_name='otas_smoobu_apartme_eb3dc5_idx',
            old_name='otas_smoobu_apartment_id_idx',
        ),
        migrations.AlterField(
            model_name='otasyncjob',
            name='job_type',
            field=models.CharField(choices=[('import_ics', 'Import ICS'), ('export_ics', 'Export ICS'), ('push_ari', 'Push ARI'), ('pull_reservations', 'Pull Reservations'), ('sync_smoobu', 'Sync Smoobu')], max_length=30),
        ),
    ]
