# Generated by Django 4.2.7 on 2025-09-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
