# Generated by Django 4.2.7 on 2025-10-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_city_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='default_check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='default_check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
