# Generated by Django 4.2.7 on 2025-10-07 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0009_reservation_promotion_code'),
        ('core', '0006_alter_hotel_enterprise_delete_enterprise'),
        ('enterprises', '0006_state_sync_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mercado_pago', 'Mercado Pago')], default='mercado_pago', max_length=30)),
                ('public_key', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=200)),
                ('integrator_id', models.CharField(blank=True, max_length=200)),
                ('is_test', models.BooleanField(default=True)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('currency_code', models.CharField(blank=True, max_length=3)),
                ('webhook_secret', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_configs', to='enterprises.enterprise')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_configs', to='core.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('mp_preference_id', models.CharField(blank=True, max_length=80)),
                ('mp_payment_id', models.CharField(blank=True, max_length=80)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('created', 'Creado'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='enterprises.enterprise')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='core.hotel')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='reservations.reservation')),
            ],
            options={
                'indexes': [models.Index(fields=['hotel', 'status'], name='payments_pa_hotel_i_8794a6_idx'), models.Index(fields=['reservation'], name='payments_pa_reserva_10122b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentgatewayconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('hotel__isnull', False)), fields=('provider', 'hotel'), name='uniq_gateway_hotel'),
        ),
        migrations.AddConstraint(
            model_name='paymentgatewayconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('enterprise__isnull', False)), fields=('provider', 'enterprise'), name='uniq_gateway_enterprise'),
        ),
    ]
