# Generated by Django 4.2.7 on 2025-10-09 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hotel_auto_check_in_enabled'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, help_text='Descripción de la política de pago')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('payment_timing', models.CharField(choices=[('confirmation', 'Al confirmar reserva'), ('days_before', 'Días antes del check-in'), ('check_in', 'Al check-in'), ('check_out', 'Al check-out'), ('mixed', 'Mixto (adelanto + saldo)')], default='confirmation', help_text='Cuándo se cobra al huésped', max_length=20)),
                ('deposit_type', models.CharField(choices=[('none', 'Sin adelanto'), ('percentage', 'Porcentaje'), ('fixed', 'Monto fijo')], default='none', help_text='Tipo de adelanto requerido', max_length=20)),
                ('deposit_value', models.DecimalField(decimal_places=2, default=0, help_text='Valor del adelanto (% o monto fijo)', max_digits=10)),
                ('deposit_due', models.CharField(choices=[('confirmation', 'Al confirmar reserva'), ('days_before', 'Días antes del check-in'), ('check_in', 'Al check-in'), ('check_out', 'Al check-out'), ('mixed', 'Mixto (adelanto + saldo)')], default='confirmation', help_text='Cuándo vence el adelanto', max_length=20)),
                ('deposit_days_before', models.PositiveIntegerField(default=0, help_text='Días antes del check-in (solo si deposit_due = days_before)')),
                ('balance_due', models.CharField(choices=[('confirmation', 'Al confirmar reserva'), ('days_before', 'Días antes del check-in'), ('check_in', 'Al check-in'), ('check_out', 'Al check-out'), ('mixed', 'Mixto (adelanto + saldo)')], default='check_in', help_text='Cuándo se cobra el saldo restante', max_length=20)),
                ('allow_partial_payments', models.BooleanField(default=False, help_text='Permitir pagos parciales')),
                ('require_payment_confirmation', models.BooleanField(default=True, help_text='Requiere confirmación de pago para confirmar reserva')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_policies', to='core.hotel')),
                ('methods', models.ManyToManyField(blank=True, help_text='Métodos de pago disponibles para esta política', related_name='policies', to='payments.paymentmethod')),
            ],
            options={
                'ordering': ['-is_default', '-is_active', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentpolicy',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_policy_hotel_name'),
        ),
    ]
