# Generated by Django 4.2.7 on 2025-10-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentmethod_paymentpolicy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentpolicy',
            options={},
        ),
        migrations.RemoveField(
            model_name='paymentpolicy',
            name='allow_partial_payments',
        ),
        migrations.RemoveField(
            model_name='paymentpolicy',
            name='description',
        ),
        migrations.RemoveField(
            model_name='paymentpolicy',
            name='payment_timing',
        ),
        migrations.RemoveField(
            model_name='paymentpolicy',
            name='require_payment_confirmation',
        ),
        migrations.AlterField(
            model_name='paymentpolicy',
            name='balance_due',
            field=models.CharField(choices=[('check_in', 'Al check-in'), ('check_out', 'Al check-out')], default='check_in', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentpolicy',
            name='deposit_days_before',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentpolicy',
            name='deposit_due',
            field=models.CharField(choices=[('confirmation', 'Al confirmar'), ('days_before', 'Días antes del check-in'), ('check_in', 'Al check-in')], default='confirmation', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentpolicy',
            name='deposit_type',
            field=models.CharField(choices=[('none', 'Sin adelanto'), ('percentage', 'Porcentaje'), ('fixed', 'Monto fijo')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentpolicy',
            name='deposit_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentpolicy',
            name='methods',
            field=models.ManyToManyField(blank=True, related_name='policies', to='payments.paymentmethod'),
        ),
    ]
