# Generated by Django 4.2.7 on 2025-10-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentpolicy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpolicy',
            name='allow_deposit',
            field=models.BooleanField(default=True, help_text='Permitir pago de depósito/seña'),
        ),
    ]
