# Generated by Django 4.2.7 on 2025-10-15 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_hotel_auto_check_in_enabled'),
        ('payments', '0004_paymentpolicy_allow_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la política', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('free_cancellation_time', models.PositiveIntegerField(default=24, help_text='Tiempo para cancelación gratuita')),
                ('free_cancellation_unit', models.CharField(choices=[('hours', 'Horas'), ('days', 'Días'), ('weeks', 'Semanas')], default='hours', max_length=10)),
                ('partial_refund_time', models.PositiveIntegerField(default=72, help_text='Tiempo para devolución parcial')),
                ('partial_refund_unit', models.CharField(choices=[('hours', 'Horas'), ('days', 'Días'), ('weeks', 'Semanas')], default='hours', max_length=10)),
                ('partial_refund_percentage', models.DecimalField(decimal_places=2, default=50.0, help_text='Porcentaje de devolución parcial', max_digits=5)),
                ('no_refund_time', models.PositiveIntegerField(default=168, help_text='Tiempo después del cual no hay devolución')),
                ('no_refund_unit', models.CharField(choices=[('hours', 'Horas'), ('days', 'Días'), ('weeks', 'Semanas')], default='hours', max_length=10)),
                ('cancellation_fee_type', models.CharField(choices=[('none', 'Sin penalidad'), ('percentage', 'Porcentaje del total'), ('fixed', 'Monto fijo'), ('first_night', 'Primera noche'), ('nights_percentage', 'Porcentaje por noche')], default='percentage', max_length=20)),
                ('cancellation_fee_value', models.DecimalField(decimal_places=2, default=10.0, help_text='Valor de la penalidad (% o monto)', max_digits=10)),
                ('allow_cancellation_after_checkin', models.BooleanField(default=False, help_text='Permitir cancelación después del check-in')),
                ('allow_cancellation_after_checkout', models.BooleanField(default=False, help_text='Permitir cancelación después del check-out')),
                ('allow_cancellation_no_show', models.BooleanField(default=True, help_text='Permitir cancelación de no-show')),
                ('allow_cancellation_early_checkout', models.BooleanField(default=False, help_text='Permitir cancelación por salida anticipada')),
                ('refund_method', models.CharField(choices=[('full', 'Devolución completa'), ('partial', 'Devolución parcial'), ('none', 'Sin devolución'), ('voucher', 'Voucher de crédito')], default='full', max_length=20)),
                ('refund_processing_days', models.PositiveIntegerField(default=7, help_text='Días para procesar devolución')),
                ('voucher_expiry_days', models.PositiveIntegerField(default=365, help_text='Días de validez del voucher')),
                ('voucher_minimum_amount', models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo para voucher', max_digits=10)),
                ('free_cancellation_message', models.TextField(blank=True, help_text='Mensaje para cancelación gratuita')),
                ('partial_refund_message', models.TextField(blank=True, help_text='Mensaje para devolución parcial')),
                ('no_refund_message', models.TextField(blank=True, help_text='Mensaje para sin devolución')),
                ('cancellation_fee_message', models.TextField(blank=True, help_text='Mensaje para penalidad de cancelación')),
                ('apply_to_all_room_types', models.BooleanField(default=True, help_text='Aplicar a todos los tipos de habitación')),
                ('room_types', models.JSONField(blank=True, default=list, help_text='Tipos de habitación específicos (si no aplica a todos)')),
                ('apply_to_all_channels', models.BooleanField(default=True, help_text='Aplicar a todos los canales')),
                ('channels', models.JSONField(blank=True, default=list, help_text='Canales específicos (si no aplica a todos)')),
                ('apply_to_all_seasons', models.BooleanField(default=True, help_text='Aplicar a todas las temporadas')),
                ('seasonal_rules', models.JSONField(blank=True, default=list, help_text='Reglas específicas por temporada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policies', to='core.hotel')),
            ],
            options={
                'verbose_name': 'Política de Cancelación',
                'verbose_name_plural': 'Políticas de Cancelación',
                'ordering': ['-is_default', '-is_active', 'name'],
                'indexes': [models.Index(fields=['hotel', 'is_active'], name='payments_ca_hotel_i_dda840_idx'), models.Index(fields=['is_default'], name='payments_ca_is_defa_e39bf7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cancellationpolicy',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_cancellation_policy_hotel_name'),
        ),
    ]
