# Generated by Django 4.2.7 on 2025-10-15 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_hotel_auto_check_in_enabled'),
        ('payments', '0005_cancellationpolicy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellationpolicy',
            name='no_refund_message',
        ),
        migrations.RemoveField(
            model_name='cancellationpolicy',
            name='partial_refund_message',
        ),
        migrations.RemoveField(
            model_name='cancellationpolicy',
            name='refund_method',
        ),
        migrations.RemoveField(
            model_name='cancellationpolicy',
            name='refund_processing_days',
        ),
        migrations.RemoveField(
            model_name='cancellationpolicy',
            name='voucher_expiry_days',
        ),
        migrations.RemoveField(
            model_name='cancellationpolicy',
            name='voucher_minimum_amount',
        ),
        migrations.AddField(
            model_name='cancellationpolicy',
            name='no_cancellation_message',
            field=models.TextField(blank=True, help_text='Mensaje para sin cancelación'),
        ),
        migrations.AddField(
            model_name='cancellationpolicy',
            name='partial_cancellation_message',
            field=models.TextField(blank=True, help_text='Mensaje para cancelación parcial'),
        ),
        migrations.CreateModel(
            name='RefundPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la política', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('full_refund_time', models.PositiveIntegerField(default=24, help_text='Tiempo para devolución completa')),
                ('full_refund_unit', models.CharField(choices=[('hours', 'Horas'), ('days', 'Días'), ('weeks', 'Semanas')], default='hours', max_length=10)),
                ('partial_refund_time', models.PositiveIntegerField(default=72, help_text='Tiempo para devolución parcial')),
                ('partial_refund_unit', models.CharField(choices=[('hours', 'Horas'), ('days', 'Días'), ('weeks', 'Semanas')], default='hours', max_length=10)),
                ('partial_refund_percentage', models.DecimalField(decimal_places=2, default=50.0, help_text='Porcentaje de devolución parcial', max_digits=5)),
                ('no_refund_time', models.PositiveIntegerField(default=168, help_text='Tiempo después del cual no hay devolución')),
                ('no_refund_unit', models.CharField(choices=[('hours', 'Horas'), ('days', 'Días'), ('weeks', 'Semanas')], default='hours', max_length=10)),
                ('refund_method', models.CharField(choices=[('cash', 'Efectivo'), ('bank_transfer', 'Transferencia Bancaria'), ('credit_card', 'Tarjeta de Crédito'), ('voucher', 'Voucher de Crédito'), ('original_payment', 'Método de Pago Original')], default='original_payment', max_length=20)),
                ('refund_processing_days', models.PositiveIntegerField(default=7, help_text='Días para procesar devolución')),
                ('voucher_expiry_days', models.PositiveIntegerField(default=365, help_text='Días de validez del voucher')),
                ('voucher_minimum_amount', models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo para voucher', max_digits=10)),
                ('full_refund_message', models.TextField(blank=True, help_text='Mensaje para devolución completa')),
                ('partial_refund_message', models.TextField(blank=True, help_text='Mensaje para devolución parcial')),
                ('no_refund_message', models.TextField(blank=True, help_text='Mensaje para sin devolución')),
                ('voucher_message', models.TextField(blank=True, help_text='Mensaje para voucher de crédito')),
                ('apply_to_all_room_types', models.BooleanField(default=True, help_text='Aplicar a todos los tipos de habitación')),
                ('room_types', models.JSONField(blank=True, default=list, help_text='Tipos de habitación específicos (si no aplica a todos)')),
                ('apply_to_all_channels', models.BooleanField(default=True, help_text='Aplicar a todos los canales')),
                ('channels', models.JSONField(blank=True, default=list, help_text='Canales específicos (si no aplica a todos)')),
                ('apply_to_all_seasons', models.BooleanField(default=True, help_text='Aplicar a todas las temporadas')),
                ('seasonal_rules', models.JSONField(blank=True, default=list, help_text='Reglas específicas por temporada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_policies', to='core.hotel')),
            ],
            options={
                'verbose_name': 'Política de Devolución',
                'verbose_name_plural': 'Políticas de Devolución',
                'ordering': ['-is_default', '-is_active', 'name'],
                'indexes': [models.Index(fields=['hotel', 'is_active'], name='payments_re_hotel_i_f4f8f6_idx'), models.Index(fields=['is_default'], name='payments_re_is_defa_46c455_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='refundpolicy',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='uniq_refund_policy_hotel_name'),
        ),
    ]
