# Generated by Django 4.2.7 on 2025-10-15 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0010_add_applied_cancellation_policy'),
        ('payments', '0006_remove_cancellationpolicy_no_refund_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del reembolso', max_digits=10)),
                ('reason', models.CharField(choices=[('cancellation', 'Cancelación de Reserva'), ('partial_cancellation', 'Cancelación Parcial'), ('overpayment', 'Sobrepago'), ('discount_applied', 'Descuento Aplicado'), ('admin_adjustment', 'Ajuste Administrativo'), ('customer_request', 'Solicitud del Cliente'), ('system_error', 'Error del Sistema')], help_text='Razón del reembolso', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', help_text='Estado del reembolso', max_length=20)),
                ('refund_method', models.CharField(help_text='Método de reembolso (cash, bank_transfer, credit_card, etc.)', max_length=30)),
                ('processing_days', models.PositiveIntegerField(default=7, help_text='Días estimados para procesar el reembolso')),
                ('external_reference', models.CharField(blank=True, help_text='Referencia externa del reembolso (ej: ID de Mercado Pago)', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el reembolso', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Fecha y hora cuando se completó el reembolso', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el reembolso', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(help_text='Pago original que se está reembolsando', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='reservations.payment')),
                ('reservation', models.ForeignKey(help_text='Reserva asociada al reembolso', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reservation', 'status'], name='payments_re_reserva_6a6857_idx'), models.Index(fields=['status', 'created_at'], name='payments_re_status_698972_idx'), models.Index(fields=['payment'], name='payments_re_payment_0f5ef3_idx')],
            },
        ),
    ]
