# Generated by Django 4.2.7 on 2025-10-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_add_refund_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpolicy',
            name='auto_cancel_days',
            field=models.PositiveIntegerField(default=7, help_text='Días después de crear la reserva para auto-cancelar si no hay pagos'),
        ),
        migrations.AddField(
            model_name='paymentpolicy',
            name='auto_cancel_enabled',
            field=models.BooleanField(default=True, help_text='Habilitar auto-cancelación de reservas pendientes sin pago'),
        ),
    ]
