# Generated by Django 4.2.7 on 2025-10-16 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_reservation_applied_cancellation_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0008_add_auto_cancel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='method',
            field=models.CharField(default='original_payment', help_text='Método de reembolso (original_payment, voucher, bank_transfer, etc.)', max_length=30),
        ),
        migrations.AddField(
            model_name='refund',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que procesó el reembolso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refund',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Monto del reembolso', max_digits=12),
        ),
        migrations.AlterField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Pago original que se está reembolsando', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='reservations.payment'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.CharField(blank=True, choices=[('cancellation', 'Cancelación de Reserva'), ('partial_cancellation', 'Cancelación Parcial'), ('overpayment', 'Sobrepago'), ('discount_applied', 'Descuento Aplicado'), ('admin_adjustment', 'Ajuste Administrativo'), ('customer_request', 'Solicitud del Cliente'), ('system_error', 'Error del Sistema')], help_text='Razón del reembolso', max_length=30, null=True),
        ),
    ]
