# Generated by Django 4.2.7 on 2025-10-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_refund_method_refund_processed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationpolicy',
            name='auto_refund_on_cancel',
            field=models.BooleanField(default=False, help_text='Procesar reembolso automáticamente al cancelar'),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='partial_refunds_allowed',
            field=models.BooleanField(default=True, help_text='Permitir reembolsos parciales'),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='refund_window_days',
            field=models.PositiveIntegerField(blank=True, help_text='Días límite para procesar reembolsos (null = sin límite)', null=True),
        ),
    ]
