# Generated by Django 4.2.7 on 2025-10-17 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0010_cancellationpolicy_auto_refund_on_cancel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='history',
            field=models.JSONField(blank=True, default=list, help_text='Historial compacto de cambios del reembolso'),
        ),
        migrations.CreateModel(
            name='RefundLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Creado'), ('status_changed', 'Estado Cambiado'), ('processing_started', 'Procesamiento Iniciado'), ('processing_completed', 'Procesamiento Completado'), ('processing_failed', 'Procesamiento Fallido'), ('external_reference_updated', 'Referencia Externa Actualizada'), ('notes_updated', 'Notas Actualizadas'), ('cancelled', 'Cancelado'), ('retry_attempt', 'Intento de Reintento'), ('gateway_error', 'Error de Pasarela'), ('manual_intervention', 'Intervención Manual')], help_text='Tipo de evento registrado', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], help_text='Estado del reembolso en este momento', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del evento')),
                ('action', models.CharField(help_text='Acción específica realizada', max_length=50)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Detalles adicionales del evento')),
                ('external_reference', models.CharField(blank=True, help_text='Referencia externa si aplica', max_length=200, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si aplica', null=True)),
                ('message', models.CharField(blank=True, help_text='Mensaje descriptivo del evento', max_length=300, null=True)),
                ('refund', models.ForeignKey(help_text='Reembolso asociado al log', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.refund')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción (null = sistema)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Reembolso',
                'verbose_name_plural': 'Logs de Reembolsos',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['refund', 'timestamp'], name='payments_re_refund__8349cc_idx'), models.Index(fields=['event_type', 'timestamp'], name='payments_re_event_t_d4c5bd_idx'), models.Index(fields=['status', 'timestamp'], name='payments_re_status_13b75b_idx')],
            },
        ),
    ]
