# Generated by Django 4.2.7 on 2025-10-18 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_hotel_auto_no_show_enabled'),
        ('reservations', '0012_add_no_show_events'),
        ('payments', '0011_refund_history_refundlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único del voucher', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del voucher', max_digits=12)),
                ('expiry_date', models.DateTimeField(help_text='Fecha de expiración del voucher')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('used', 'Usado'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='active', help_text='Estado del voucher', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='Fecha y hora cuando se usó el voucher', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el voucher', null=True)),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto restante del voucher (para vouchers parcialmente usados)', max_digits=12, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el voucher', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(help_text='Hotel que emitió el voucher', on_delete=django.db.models.deletion.CASCADE, related_name='refund_vouchers', to='core.hotel')),
                ('original_refund', models.ForeignKey(blank=True, help_text='Reembolso que generó este voucher', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_vouchers', to='payments.refund')),
                ('used_by', models.ForeignKey(blank=True, help_text='Usuario que usó el voucher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_vouchers', to=settings.AUTH_USER_MODEL)),
                ('used_in_reservation', models.ForeignKey(blank=True, help_text='Reserva donde se usó el voucher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_vouchers', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Voucher de Reembolso',
                'verbose_name_plural': 'Vouchers de Reembolso',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='refund',
            name='generated_voucher',
            field=models.ForeignKey(blank=True, help_text='Voucher generado por este reembolso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_refund', to='payments.refundvoucher'),
        ),
        migrations.AddIndex(
            model_name='refundvoucher',
            index=models.Index(fields=['code'], name='payments_re_code_c66ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='refundvoucher',
            index=models.Index(fields=['hotel', 'status'], name='payments_re_hotel_i_950436_idx'),
        ),
        migrations.AddIndex(
            model_name='refundvoucher',
            index=models.Index(fields=['status', 'expiry_date'], name='payments_re_status_583f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='refundvoucher',
            index=models.Index(fields=['original_refund'], name='payments_re_origina_496d7f_idx'),
        ),
    ]
