# Generated by Django 4.2.7 on 2025-10-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_refundvoucher_refund_generated_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='is_production',
            field=models.BooleanField(default=False, help_text='Indica si esta configuración es para producción'),
        ),
    ]
