# Generated by Django 4.2.7 on 2025-10-20 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_hotel_auto_no_show_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0013_add_voucher_code'),
        ('payments', '0013_paymentgatewayconfig_is_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransferPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto de la transferencia', max_digits=12)),
                ('transfer_date', models.DateField(help_text='Fecha de la transferencia bancaria')),
                ('cbu_iban', models.CharField(help_text='CBU o IBAN de la cuenta destino', max_length=50)),
                ('bank_name', models.CharField(blank=True, help_text='Nombre del banco (opcional)', max_length=100)),
                ('receipt_file', models.FileField(help_text='Archivo del comprobante de transferencia', upload_to='bank_transfers/receipts/%Y/%m/%d/')),
                ('receipt_filename', models.CharField(blank=True, help_text='Nombre original del archivo', max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Comprobante Subido'), ('pending_review', 'Pendiente de Revisión'), ('confirmed', 'Confirmada'), ('rejected', 'Rechazada'), ('processing', 'Procesando')], default='uploaded', help_text='Estado de la transferencia', max_length=20)),
                ('ocr_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto extraído por OCR del comprobante', max_digits=12, null=True)),
                ('ocr_cbu', models.CharField(blank=True, help_text='CBU extraído por OCR del comprobante', max_length=50)),
                ('ocr_confidence', models.FloatField(blank=True, help_text='Nivel de confianza del OCR (0-1)', null=True)),
                ('is_amount_valid', models.BooleanField(blank=True, help_text='Si el monto coincide con el esperado', null=True)),
                ('is_cbu_valid', models.BooleanField(blank=True, help_text='Si el CBU coincide con el esperado', null=True)),
                ('validation_notes', models.TextField(blank=True, help_text='Notas de la validación')),
                ('external_reference', models.CharField(blank=True, help_text='Referencia externa de la transferencia', max_length=200)),
                ('payment_reference', models.CharField(blank=True, help_text='Referencia del pago asociado', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Fecha de revisión', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre la transferencia')),
                ('history', models.JSONField(blank=True, default=list, help_text='Historial de cambios de la transferencia')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que subió el comprobante', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(help_text='Hotel de la reserva', on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfers', to='core.hotel')),
                ('reservation', models.ForeignKey(help_text='Reserva asociada a la transferencia', on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfers', to='reservations.reservation')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Usuario que revisó el comprobante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bank_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia Bancaria',
                'verbose_name_plural': 'Transferencias Bancarias',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reservation', 'status'], name='payments_ba_reserva_06a83f_idx'), models.Index(fields=['hotel', 'status'], name='payments_ba_hotel_i_8cdbda_idx'), models.Index(fields=['status', 'created_at'], name='payments_ba_status_b789e6_idx'), models.Index(fields=['transfer_date'], name='payments_ba_transfe_05fedf_idx')],
            },
        ),
    ]
