# Generated by Django 4.2.7 on 2025-10-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_banktransferpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransferpayment',
            name='receipt_url',
            field=models.URLField(blank=True, help_text='URL completa del comprobante (Cloudinary o local)'),
        ),
        migrations.AddField(
            model_name='banktransferpayment',
            name='storage_type',
            field=models.CharField(choices=[('local', 'Local'), ('cloudinary', 'Cloudinary')], default='local', help_text='Tipo de almacenamiento del archivo', max_length=20),
        ),
    ]
