# Generated by Django 4.2.7 on 2025-10-21 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_hotel_auto_no_show_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0015_banktransferpayment_receipt_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_date', models.DateField(help_text='Fecha de la conciliación')),
                ('csv_file', models.FileField(upload_to='bank_reconciliations/%Y/%m/%d/')),
                ('csv_filename', models.CharField(max_length=255)),
                ('csv_file_size', models.PositiveIntegerField()),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('matched_transactions', models.PositiveIntegerField(default=0)),
                ('unmatched_transactions', models.PositiveIntegerField(default=0)),
                ('pending_review_transactions', models.PositiveIntegerField(default=0)),
                ('error_transactions', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completada'), ('failed', 'Fallida'), ('manual_review', 'Revisión Manual')], default='pending', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_notes', models.TextField(blank=True, help_text='Notas del procesamiento')),
                ('error_details', models.JSONField(default=dict, help_text='Detalles de errores encontrados')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_reconciliations', to='core.hotel')),
            ],
            options={
                'ordering': ['-reconciliation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('is_matched', models.BooleanField(default=False)),
                ('is_reversal', models.BooleanField(default=False, help_text='Indica si es una reversión (monto negativo)')),
                ('match_confidence', models.FloatField(blank=True, help_text='Confianza del match (0-100)', null=True)),
                ('match_type', models.CharField(blank=True, choices=[('exact', 'Exacto'), ('fuzzy', 'Aproximado'), ('partial', 'Parcial'), ('manual', 'Manual')], max_length=20, null=True)),
                ('matched_payment_id', models.PositiveIntegerField(blank=True, null=True)),
                ('matched_payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('matched_reservation_id', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_difference_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.bankreconciliation')),
            ],
            options={
                'ordering': ['transaction_date', 'amount'],
            },
        ),
        migrations.CreateModel(
            name='BankReconciliationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('csv_uploaded', 'CSV Subido'), ('processing_started', 'Procesamiento Iniciado'), ('auto_matched', 'Match Automático'), ('manual_matched', 'Match Manual'), ('pending_review', 'Pendiente de Revisión'), ('unmatched', 'Sin Match'), ('partial_match', 'Match Parcial'), ('reversal_detected', 'Reversión Detectada'), ('processing_completed', 'Procesamiento Completado'), ('error', 'Error')], max_length=30)),
                ('event_description', models.CharField(max_length=500)),
                ('bank_transaction_id', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_id', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reservation_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('csv_filename', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payments.bankreconciliation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankReconciliationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_match_date_tolerance', models.PositiveIntegerField(default=1, help_text='Días de tolerancia para match exacto')),
                ('fuzzy_match_amount_tolerance_percent', models.FloatField(default=0.5, help_text='Tolerancia de monto para match fuzzy (%)')),
                ('fuzzy_match_date_tolerance', models.PositiveIntegerField(default=2, help_text='Días de tolerancia para match fuzzy')),
                ('partial_match_amount_tolerance_percent', models.FloatField(default=1.0, help_text='Tolerancia de monto para match parcial (%)')),
                ('partial_match_date_tolerance', models.PositiveIntegerField(default=3, help_text='Días de tolerancia para match parcial')),
                ('auto_confirm_threshold', models.FloatField(default=90.0, help_text='Umbral para confirmación automática (%)')),
                ('pending_review_threshold', models.FloatField(default=70.0, help_text='Umbral para revisión manual (%)')),
                ('default_currency', models.CharField(default='ARS', max_length=3)),
                ('currency_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Tipo de cambio USD/ARS', max_digits=10, null=True)),
                ('currency_rate_date', models.DateField(blank=True, help_text='Fecha del tipo de cambio', null=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('notification_threshold_percent', models.FloatField(default=10.0, help_text='Umbral para notificación de errores (%)')),
                ('notification_emails', models.JSONField(default=list, help_text='Emails para notificaciones')),
                ('csv_encoding', models.CharField(default='utf-8', max_length=20)),
                ('csv_separator', models.CharField(default=',', max_length=5)),
                ('csv_columns', models.JSONField(default=list, help_text='Columnas esperadas en el CSV')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_configs', to='core.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.PositiveIntegerField()),
                ('payment_type', models.CharField(max_length=50)),
                ('reservation_id', models.PositiveIntegerField()),
                ('match_type', models.CharField(choices=[('exact', 'Exacto'), ('fuzzy', 'Aproximado'), ('partial', 'Parcial'), ('manual', 'Manual')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('amount_difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_difference_days', models.IntegerField(default=0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_manual', models.BooleanField(default=False)),
                ('manual_approved_at', models.DateTimeField(blank=True, null=True)),
                ('manual_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='payments.banktransaction')),
                ('manual_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='payments.bankreconciliation')),
            ],
            options={
                'indexes': [models.Index(fields=['reconciliation', 'is_confirmed'], name='payments_re_reconci_e218a3_idx'), models.Index(fields=['payment_id', 'payment_type'], name='payments_re_payment_f05f11_idx')],
                'unique_together': {('bank_transaction', 'payment_id', 'payment_type')},
            },
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['reconciliation', 'is_matched'], name='payments_ba_reconci_9a939f_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['transaction_date', 'amount'], name='payments_ba_transac_461a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['is_reversal'], name='payments_ba_is_reve_06954e_idx'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliationlog',
            index=models.Index(fields=['reconciliation', 'event_type'], name='payments_ba_reconci_48eb59_idx'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliationlog',
            index=models.Index(fields=['created_at'], name='payments_ba_created_fc1dce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankreconciliationconfig',
            unique_together={('hotel',)},
        ),
        migrations.AddIndex(
            model_name='bankreconciliation',
            index=models.Index(fields=['hotel', 'reconciliation_date'], name='payments_ba_hotel_i_e2eabd_idx'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliation',
            index=models.Index(fields=['status'], name='payments_ba_status_caedbc_idx'),
        ),
    ]
