# Generated by Django 4.2.7 on 2025-10-21 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_add_voucher_code'),
        ('core', '0008_hotel_auto_no_show_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0016_bankreconciliation_banktransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostnetTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_id', models.CharField(help_text='ID único del terminal', max_length=50, unique=True)),
                ('terminal_name', models.CharField(help_text='Nombre descriptivo del terminal', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('maintenance', 'Mantenimiento'), ('error', 'Error')], default='active', max_length=20)),
                ('auto_settlement', models.BooleanField(default=True, help_text='Settlement automático')),
                ('settlement_hour', models.TimeField(default='23:00', help_text='Hora de settlement diario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postnet_terminals', to='core.hotel')),
            ],
            options={
                'verbose_name': 'Terminal POSTNET',
                'verbose_name_plural': 'Terminales POSTNET',
                'ordering': ['terminal_name'],
            },
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='provider',
            field=models.CharField(choices=[('mercado_pago', 'Mercado Pago'), ('postnet', 'POSTNET')], default='mercado_pago', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('created', 'Creado'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('pending_settlement', 'Pendiente de Liquidación')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PostnetSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(help_text='ID del batch de settlement', max_length=100)),
                ('settlement_date', models.DateField(help_text='Fecha del settlement')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('partial', 'Parcial')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('approved_transactions', models.PositiveIntegerField(default=0)),
                ('failed_transactions', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Notas del settlement')),
                ('error_details', models.JSONField(default=dict, help_text='Detalles de errores')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postnet_settlements', to='core.hotel')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='payments.postnetterminal')),
            ],
            options={
                'verbose_name': 'Settlement POSTNET',
                'verbose_name_plural': 'Settlements POSTNET',
                'ordering': ['-settlement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostnetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='ID único de la transacción', max_length=100)),
                ('external_reference', models.CharField(help_text='Referencia externa (terminal_id|batch)', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto de la transacción', max_digits=12)),
                ('status', models.CharField(choices=[('pending_settlement', 'Pendiente de Liquidación'), ('approved', 'Aprobada'), ('failed', 'Fallida'), ('cancelled', 'Cancelada')], default='pending_settlement', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('terminal_response', models.JSONField(default=dict, help_text='Respuesta del terminal')),
                ('settlement_response', models.JSONField(default=dict, help_text='Respuesta del settlement')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Número de reintentos')),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('max_retries', models.PositiveIntegerField(default=3, help_text='Máximo número de reintentos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Notas de la transacción')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postnet_transactions', to='core.hotel')),
                ('payment_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postnet_transactions', to='payments.paymentintent')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postnet_transactions', to='reservations.reservation')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.postnetsettlement')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.postnetterminal')),
            ],
            options={
                'verbose_name': 'Transacción POSTNET',
                'verbose_name_plural': 'Transacciones POSTNET',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['terminal', 'status'], name='payments_po_termina_dfce4c_idx'), models.Index(fields=['reservation'], name='payments_po_reserva_4ebeef_idx'), models.Index(fields=['external_reference'], name='payments_po_externa_07d285_idx'), models.Index(fields=['status', 'created_at'], name='payments_po_status_658971_idx')],
                'unique_together': {('terminal', 'transaction_id')},
            },
        ),
        migrations.AddIndex(
            model_name='postnetterminal',
            index=models.Index(fields=['hotel', 'is_active'], name='payments_po_hotel_i_690efc_idx'),
        ),
        migrations.AddIndex(
            model_name='postnetterminal',
            index=models.Index(fields=['terminal_id'], name='payments_po_termina_7c1b98_idx'),
        ),
        migrations.AddIndex(
            model_name='postnetsettlement',
            index=models.Index(fields=['terminal', 'settlement_date'], name='payments_po_termina_871718_idx'),
        ),
        migrations.AddIndex(
            model_name='postnetsettlement',
            index=models.Index(fields=['status'], name='payments_po_status_b3609d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postnetsettlement',
            unique_together={('terminal', 'batch_id')},
        ),
    ]
