# Generated by Django 4.2.7 on 2025-10-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_postnetterminal_alter_paymentgatewayconfig_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postnetterminal',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='postnetterminal',
            name='hotel',
        ),
        migrations.AlterUniqueTogether(
            name='postnettransaction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postnettransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='postnettransaction',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='postnettransaction',
            name='payment_intent',
        ),
        migrations.RemoveField(
            model_name='postnettransaction',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='postnettransaction',
            name='settlement',
        ),
        migrations.RemoveField(
            model_name='postnettransaction',
            name='terminal',
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='provider',
            field=models.CharField(choices=[('mercado_pago', 'Mercado Pago')], default='mercado_pago', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('created', 'Creado'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='PostnetSettlement',
        ),
        migrations.DeleteModel(
            name='PostnetTerminal',
        ),
        migrations.DeleteModel(
            name='PostnetTransaction',
        ),
    ]
