# Generated by Django 4.2.7 on 2025-10-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_remove_postnetterminal_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='receipt_pdf_url',
            field=models.URLField(blank=True, help_text='URL del comprobante PDF generado', null=True),
        ),
    ]
