# Generated by Django 4.2.7 on 2025-10-25 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_hotel_logo'),
        ('payments', '0019_add_receipt_pdf_url_to_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Número de comprobante serio (ej: C-0001-000045)', max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ReceiptNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(choices=[('R', 'Recibo de Seña/Pago'), ('C', 'Comprobante de Devolución'), ('V', 'Voucher de Crédito'), ('INT', 'Comprobante Interno')], help_text='Tipo de comprobante', max_length=10)),
                ('series', models.PositiveIntegerField(default=1, help_text='Número de serie (0001-9999)')),
                ('current_number', models.PositiveIntegerField(default=0, help_text='Último número usado en esta serie')),
                ('is_active', models.BooleanField(default=True, help_text='Si esta secuencia está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(help_text='Hotel al que pertenece esta secuencia', on_delete=django.db.models.deletion.CASCADE, related_name='receipt_sequences', to='core.hotel')),
            ],
            options={
                'ordering': ['hotel', 'receipt_type', 'series'],
                'unique_together': {('hotel', 'receipt_type', 'series')},
            },
        ),
    ]
