# Generated by Django 4.2.7 on 2025-10-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_refund_receipt_number_receiptnumbersequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptnumbersequence',
            name='receipt_type',
            field=models.CharField(choices=[('S', 'Recibo de Seña'), ('P', 'Recibo de Pago Total'), ('D', 'Comprobante de Devolución'), ('C', 'Comprobante de Cancelación'), ('V', 'Voucher de Crédito'), ('INT', 'Comprobante Interno')], help_text='Tipo de comprobante', max_length=10),
        ),
    ]
