# Generated by Django 4.2.7 on 2025-11-28 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_alter_hotel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_phone', models.CharField(help_text='Teléfono del huésped en formato E.164', max_length=32)),
                ('guest_name', models.CharField(blank=True, max_length=120)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('state', models.CharField(choices=[('asking_checkin', 'Solicitando check-in'), ('asking_checkout', 'Solicitando check-out'), ('asking_guests', 'Solicitando cantidad de huéspedes'), ('asking_guest_name', 'Solicitando nombre del huésped'), ('asking_guest_email', 'Solicitando email del huésped'), ('confirmation', 'Esperando confirmación'), ('completed', 'Completada'), ('abandoned', 'Abandonada')], default='asking_checkin', max_length=40)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('language', models.CharField(default='es', max_length=10)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_sessions', to='core.hotel')),
            ],
            options={
                'verbose_name': 'Sesión de Chatbot',
                'verbose_name_plural': 'Sesiones de Chatbot',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['hotel', 'guest_phone'], name='chatbot_cha_hotel_i_facb9c_idx'), models.Index(fields=['is_active', 'updated_at'], name='chatbot_cha_is_acti_166182_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('hotel', 'guest_phone'), name='unique_active_chatbot_session_per_guest'),
        ),
    ]
