# Generated by Django 4.2.7 on 2025-12-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatbotprovideraccount'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatbotprovideraccount',
            new_name='chatbot_cha_provide_0804fa_idx',
            old_name='chatbot_cha_provide_idx',
        ),
        migrations.RenameIndex(
            model_name='chatbotprovideraccount',
            new_name='chatbot_cha_phone_n_c7702c_idx',
            old_name='chatbot_cha_phone_idx',
        ),
    ]
